server:
  port: 8080

spring:
  application:
    name: gcp-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgres
    password: Pol1star
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate:
          show_sql=true:
          ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
